version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Gotu@2305@#)%
      POSTGRES_DB: marketdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  zookeeper:
      image: bitnami/zookeeper:3.8
      ports:
        - "2181:2181"
      environment:
        - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
      image: bitnami/kafka:3.4
      ports:
        - "9092:9092"
      environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
        - KAFKA_LISTENERS=PLAINTEXT://:9092
        - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper

volumes:
  pgdata:
